In [4]:
import numpy as np

# list vs numpy speed test

In [5]:
from time import process_time

In [4]:
#list speed

In [6]:
py_list = [i for i in range(10000)]
start_time = process_time()
py_list = [i+5 for i in py_list]
end_time = process_time()
print(end_time - start_time)

0.0002562790000000259


In [11]:
#numpy speed

In [9]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array += 5
end_time = process_time()
print(end_time - start_time)

5.583799999997474e-05


In [10]:
#list 

In [12]:
list1 = [1,2,3]
print(list1)
type(list1)

[1, 2, 3]


list

In [ ]:
#numpy array

In [11]:
np_array = np.array([1,2,3,4,5]) #syntax ([])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [15]:
np_array = np.array([(1,2,3),(3,5,6)])
print(np_array)
type(np_array)

[[1 2 3]
 [3 5 6]]


numpy.ndarray

In [16]:
a = np.array([1,2,6])
print(a)

[1 2 6]


In [18]:
a.shape

(3,)

In [20]:
b= np.array([(1,7,9),(5,9,0)])
print(b)

[[1 7 9]
 [5 9 0]]


In [21]:
b.shape

(2, 3)

In [22]:
c = np.array ([(1,2,3,6),(3,7,4,4)],dtype = float)
print(c)

[[1. 2. 3. 6.]
 [3. 7. 4. 4.]]


In [23]:
#create a numpy array with zeroes

In [26]:
c = np.zeros((4,5),dtype = int)
print(c)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [27]:
d = np.ones((4,6))
print(d)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [28]:
#in upper default is float we need to define dtype everytime

In [29]:
e = np.full((3,5),7) #to create a array with a default val
print(e)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [32]:
a = np.eye((3),dtype = int)
print(a) #identity matrix with 3x3

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [34]:
#array with random values
a = np.random.random((4,5))
print(a)

[[0.43777676 0.07013095 0.99007102 0.33270163 0.76511879]
 [0.81176548 0.84375919 0.89745142 0.43932984 0.23049484]
 [0.23583511 0.6192202  0.3367097  0.83282114 0.38215467]
 [0.4286828  0.41019823 0.87061225 0.93808977 0.53189968]]


In [35]:
#array with random value within a specific range
b = np.random.randint(10,40,(2,3))
print(b)

[[29 14 16]
 [24 24 19]]


In [37]:
#np_array --> evenly spaced vals tell how much values you require
b = np.linspace(10,30,4)
print(b)

[10.         16.66666667 23.33333333 30.        ]


In [38]:
#np_array --> aranges wrt val provided and last is excluded
c = np.arange(10,50,4)
print(c)

[10 14 18 22 26 30 34 38 42 46]


In [39]:
#convert a list to numpy array 
list1 = [1,2,3]
np_array = np.asarray(list1)
print(np_array)
type(np_array)

[1 2 3]


numpy.ndarray

# analyzing array

In [40]:
c = np.random.randint(20,70,(3,3))

In [41]:
print(c)

[[56 54 44]
 [53 30 40]
 [33 28 67]]


In [42]:
#array shape
print(c.shape)

(3, 3)


In [43]:
#array dimensions
print(c.ndim)

2


In [44]:
#array elements datatype
print(c.dtype)

int64


In [46]:
#array size = total elements present
print(c.size)

9


# mathematical operations on array

In [47]:
list1 = [1,2,5,3,4]
list2 = [6,9,0,8,7]
print(list1 + list2) #concatenate two lists

[1, 2, 5, 3, 4, 6, 9, 0, 8, 7]


In [48]:
c = np.random.randint(0,10,(3,3))
d = np.random.randint(10,20,(3,3))
print(c)
print(d)

[[9 9 5]
 [3 6 3]
 [9 6 4]]
[[11 19 15]
 [19 14 14]
 [17 17 10]]


In [49]:
print(c+d)
print(c-d)
print(c*d)
print(c/d)

[[20 28 20]
 [22 20 17]
 [26 23 14]]
[[ -2 -10 -10]
 [-16  -8 -11]
 [ -8 -11  -6]]
[[ 99 171  75]
 [ 57  84  42]
 [153 102  40]]
[[0.81818182 0.47368421 0.33333333]
 [0.15789474 0.42857143 0.21428571]
 [0.52941176 0.35294118 0.4       ]]


In [51]:
print(np.add(c,d))
print(np.subtract(c,d))
print(np.multiply(c,d))
print(np.divide(c,d)) 
#another way of doing basic mathematical operatons

[[20 28 20]
 [22 20 17]
 [26 23 14]]
[[ -2 -10 -10]
 [-16  -8 -11]
 [ -8 -11  -6]]
[[ 99 171  75]
 [ 57  84  42]
 [153 102  40]]
[[0.81818182 0.47368421 0.33333333]
 [0.15789474 0.42857143 0.21428571]
 [0.52941176 0.35294118 0.4       ]]


# array manipulation

In [52]:
a = np.random.randint(0,10,(3,4))
print(a)
print(a.shape)

[[7 2 8 5]
 [8 4 7 0]
 [8 6 2 3]]
(3, 4)


In [53]:
trans = np.transpose(a)
print(trans)
print(trans.shape)

[[7 8 8]
 [2 4 6]
 [8 7 2]
 [5 0 3]]
(4, 3)


In [54]:
trans2 = a.T
print(trans2)
print(trans2.shape)

[[7 8 8]
 [2 4 6]
 [8 7 2]
 [5 0 3]]
(4, 3)


In [55]:
#array reshaping
b = np.random.randint(10,20,(4,5))
print(b)
print(b.shape)

[[11 11 15 19 18]
 [15 16 10 18 19]
 [15 13 17 10 14]
 [14 11 13 14 11]]
(4, 5)


In [56]:
c = b.reshape(5,4)
print(c)
print(c.shape)

[[11 11 15 19]
 [18 15 16 10]
 [18 19 15 13]
 [17 10 14 14]
 [11 13 14 11]]
(5, 4)
