# Numpy

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

# What is an array

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [1]:
#import numpy 
import numpy as np

In [10]:
my_list=[1,2,3,4,5]

In [11]:
arr=np.array(my_list)

In [12]:
arr

array([1, 2, 3, 4, 5])

In [13]:
type(arr)

numpy.ndarray

In [16]:
my_lst1=[1,2,3,4]
my_lst2=[2,4,6,7]
my_lst3=[4,9,5,2]
arr1=np.array([my_lst1,my_lst2,my_lst3])

In [63]:
arr1  #for checking multidimensional nature of array count [] at starting and closing. it will tell the dimension of array

array([  1,   2,   3, 250, 250])

In [18]:
type(arr1)

numpy.ndarray

In [20]:
#check shape of array
arr1.shape

(3, 4)

In [21]:
arr1.reshape(4,3)

array([[1, 2, 3],
       [4, 2, 4],
       [6, 7, 4],
       [9, 5, 2]])

# Indexing
indexing is done with []
and syntax 
arr1[initial row:final row,initial col:final col]

In [22]:
## Accessing the array elements
arr

array([1, 2, 3, 4, 5])

In [23]:
arr[2]

3

In [24]:
arr1

array([[1, 2, 3, 4],
       [2, 4, 6, 7],
       [4, 9, 5, 2]])

In [27]:
arr1[0:2,0:2]

array([[1, 2],
       [2, 4]])

In [28]:
#lets extract 3,6 and 4,7 from arr1

In [32]:
arr1[0:2,2:] #indexing start with 0 and final means that row/col will be excluded so for getting '6' we wrote 2 as elements of those will be excluded

array([[3, 4],
       [6, 7]])

In [33]:
arr

array([1, 2, 3, 4, 5])

In [34]:
arr[3:]=100 #it will replace every value with 100 starting point is index = 3

In [35]:
arr

array([  1,   2,   3, 100, 100])

In [36]:
#copy function or broadcasting

In [37]:
arr1=arr

In [38]:
arr1[3:]=300

In [39]:
arr1

array([  1,   2,   3, 300, 300])

In [40]:
arr

array([  1,   2,   3, 300, 300])

In [42]:
#from above we can see that values of arr got replaced too as arr1. array is a reference type.

In [43]:
#thus to avoid this change we use copy()

In [44]:
arr1=arr.copy()

In [45]:
print(arr)
arr1[3:]=250
print(arr1)

[  1   2   3 300 300]
[  1   2   3 250 250]


In [46]:
arr

array([  1,   2,   3, 300, 300])

In [47]:
#now the values of arr remain unchanged as we used copy()

# mathematical operations on array

In [48]:
arr

array([  1,   2,   3, 300, 300])

In [52]:
print(arr+2)
print(arr-2)
print(arr*2)
print(arr**2)
print(arr/2)
print(arr<2)
print(arr>2)

[  3   4   5 302 302]
[ -1   0   1 298 298]
[  2   4   6 600 600]
[    1     4     9 90000 90000]
[  0.5   1.    1.5 150.  150. ]
[ True False False False False]
[False False  True  True  True]


In [54]:
#to get exact value in < or > instead of boolean value
#use
arr[arr<2] #used in EDA

array([1])

In [58]:
np.arange(0,10) #arange is used for Returning evenly spaced values within a given interval.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.arange(0,10,step=2)

array([0, 2, 4, 6, 8])

In [62]:
np.arange(0,10).reshape(5,2) 

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [66]:
np.ones((2),dtype=int) #for creating arrayswith only 1s

array([1, 1])

In [65]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [70]:
np.linspace(1,10,20) #for randomly selecting 20 no. b/w 1 and 10 default type = float 

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])